import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import GameBoard from "../components/GameBoard";
import Key from "../components/Key";
import Keyboard from "../components/Keyboard";

const ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";

export default function Home() {
  const [guess, setGuess] = useState();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <GameBoard />

      <Keyboard setGuess={setGuess} />

      <div>Guess: {guess}</div>
    </>
  );
}
